#!/bin/bash
#SBATCH --nodes 1
#SBATCH --partition physical
#SBATCH --mem 32G
#SBATCH --time 0-2:00:00
#SBATCH -A punim1413

module load gcccore/8.3.0
module load python/3.8.2
module load web_proxy

version=$(python --version)
echo $version

DATASETS="('PMCC-HN-TEST-LOC','PMCC-HN-TRAIN-LOC')" # Code links from 'training' set to nifti set.
region=(
    'BrachialPlexus_L'  # 0
    'BrachialPlexus_R'  # 1
    'Brain'             # 2
    'BrainStem'         # 3
    'Cochlea_L'         # 4
    'Cochlea_R'         # 5
    'Lens_L'            # 6
    'Lens_R'            # 7
    'Mandible'          # 8
    'OpticNerve_L'      # 9
    'OpticNerve_R'      # 10
    'OralCavity'        # 11
    'Parotid_L'         # 12
    'Parotid_R'         # 13
    'SpinalCord'        # 14
    'Submandibular_L'   # 15
    'Submandibular_R'   # 16
)
REGION=${REGIONS[$SLURM_ARRAY_TASK_ID]}
LOCALISER="('localiser-$REGION','public-1gpu-150epochs','BEST')"
# MODEL='clinical'
N_FOLDS=5
# N_TRAIN=5
SCRIPT_DIR="/data/gpfs/projects/punim1413/medical-imaging/scripts"
# TEST_FOLD=0
if [ "$MODEL" = "public" ]; then
    run_name="public-1gpu-150epochs"
else
    run_name="$MODEL-fold-$TEST_FOLD-samples-$N_TRAIN"
fi
SEGMENTER="('segmenter-$REGION','$run_name','BEST')"

python $SCRIPT_DIR/evaluate/nifti/segmenter/evaluate_from_loader.py \
    --datasets $DATASETS \
    --localiser $LOCALISER \
    --n_folds $N_FOLDS \
    --region $REGION \
    --segmenter $SEGMENTER \
    --test_fold $TEST_FOLD
