#! /usr/bin/env bash

BOTTLENECK=8
DATASETS="['CIRCLES']"
MODEL_NAME="auto-encoder-circles"
n_EPOCHS=400
n_GPUS=0
n_NODES=1
n_WORKERS=4
n_SUBSET=None
RESUME=False
RESUME_CHECKPOINT=None
RUN_NAME="test"
SCRIPT_DIR="/data/gpfs/projects/punim1413/medical-imaging/scripts"
USE_LOGGER=False

python $SCRIPT_DIR/train/auto_encoder --slurm_job_id $SLURM_JOB_ID --model_name $MODEL_NAME --run_name $RUN_NAME --datasets $DATASETS --bottleneck $BOTTLENECK \
    --n_epochs $n_EPOCHS --n_gpus $n_GPUS --n_nodes $n_NODES --n_subset $n_SUBSET --n_workers $n_WORKERS --region $REGION --resume $RESUME \
    --resume_checkpoint $RESUME_CHECKPOINT --use_logger $USE_LOGGER
