#! /usr/bin/env bash

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")"; cd ..; pwd -P )
cd $parent_path

DATASET="PMCC-HN-TEST"
region=(
    # 'BrachialPlexus_L'  # 0
    # 'BrachialPlexus_R'  # 1
    # 'Brain'             # 2
    # 'BrainStem'         # 3
    # 'Cochlea_L'         # 4
    # 'Cochlea_R'         # 5
    # 'Lens_L'            # 6
    # 'Lens_R'            # 7
    # 'Mandible'          # 8
    'OpticNerve_L'      # 9
    'OpticNerve_R'      # 10
    # 'OralCavity'        # 11
    # 'Parotid_L'         # 12
    # 'Parotid_R'         # 13
    # 'SpinalCord'        # 14
    # 'Submandibular_L'   # 15
    # 'Submandibular_R'   # 16
)
LOCALISERS=()
for i in "${!REGIONS[@]}"; do
    localiser="('localiser-${REGIONS[i]}','public-large-400epochs','BEST')"
    LOCALISERS+=($localiser)
done

# Convert to string.
region=$(IFS=$','; echo "${REGIONS[*]}")
LOCALISERS=$(IFS=$','; echo "${LOCALISERS[*]}")

python localiser_figures --dataset $DATASET --regions $REGIONS --localisers $LOCALISERS

