#!/usr/bin/env python
import fire
import os
import sys

root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '....'))
sys.path.append(root_dir)

from hnas.training.localiser_instance_norm import train_localiser

if __name__ == '__main__':
    fire.Fire(train_localiser)

# Sample args:
# --datasets "['HN1-LOC','HNSCC-LOC']" --n_gpus 4 --n_nodes 1 --n_workers 4 --use_logger True
